# Site settings
title:       SIMLab
email:       hello@simlab.org
description: "We help make technology work for everyone."
baseurl:     #"/staging"
url:         "http://simlab.org"
date_format: "%b %-d, %Y"

# Plugins
gems: ['jekyll-paginate']

# Google services
google_analytics: UA-54445094-1
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: simlab

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
facebook_username: thesimlab
github_username:
bitbucket_username:
stackoverflow_id:
twitter_username: simlab
google_plus_id:
linkedin_username: social-impact-lab
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text:
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: true
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
relative_permalinks: false
include: ['_pages']
exclude: [vendor]
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
paginate_path: "/blog/page:num/"
sass:
  compressed: true

collections:
 courses:
   title: Courses
   description: "Brief Explanation of section"
   output: true
   permalink: /courses/:name/
   root: /courses/
 casestudies:
   title: Case Studies
   description: "Brief Explanation of section"
   output: true
   permalink: /casestudies/:name/
   root: /casestudies/
 documentation:
   title: Guides and Frameworks
   description: "Brief Explanation of section"
   output: true
   permalink: /guidesandframeworks/:name/
   root: /guidesandframeworks/
 resources:
   title: Resources
   description: "Brief Explanation of section"
   output: true
   permalink: /resources/:name/
   root: /resources/
